CREATE TABLE IF NOT EXISTS stock_type (
id SERIAL PRIMARY KEY,
type VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS stock (
id SERIAL PRIMARY KEY,
symbol VARCHAR(20) UNIQUE NOT NULL,
type INTEGER NOT NULL,
name VARCHAR(100),
price NUMERIC DEFAULT 0,
dayHigh NUMERIC DEFAULT 0,
dayLow NUMERIC DEFAULT 0,
change NUMERIC DEFAULT 0,
changeInPercent NUMERIC DEFAULT 0,
marketcap NUMERIC DEFAULT 0,
volume BIGINT DEFAULT 0,
FOREIGN KEY (type) REFERENCES stock_type(id)
);

CREATE TABLE IF NOT EXISTS customer (
id SERIAL PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(250) UNIQUE NOT NULL,
password VARCHAR(250) NOT NULL,
role VARCHAR(50) NOT NULL,
creation_time DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_stock (
customer_id INTEGER NOT NULL,
stock_symbol VARCHAR(20) NOT NULL,
amount NUMERIC NOT NULL,
PRIMARY KEY (customer_id, stock_symbol),
FOREIGN KEY (customer_id) REFERENCES customer (id),
FOREIGN KEY (stock_symbol) REFERENCES stock(symbol)
);